title: Weimode
email: 1820349978@qq.com
description: 'T.R.Y'
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
tagline: 'T.R.Y'
baseurl: ""
url: ""

navigation: # Navigation links
  - {name: 'Home', link: '/'}

hero_img: darken.jpg

github_username:  weimode

markdown: kramdown
theme: jekyll-sleek
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: ["deploy"]
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - deploy
